### PR TITLE
Add FOOBAR to pull_request_template.md

### PR DESCRIPTION
**Pull request by florkbr**
## Description

I am proposing we add the H1 heading "foobar" to the PR template  as requested in the ticket linked below. To see the change, you can preview the PR template in this PR.

https://issues.redhat.com/browse/RHCLOUD-XXXXX

### Before
image

### After
image

## Checklist ☑️
- [x] PR only fixes one issue or story (open new ticket & PR for others)
- [x] Diff reviewed for extraneous console statements, comments, files, incorrect file renaming (not using `git mv`), whitespace, etc.
- [x] All PR checks pass locally
  - [x] Build
  - [x] Lint
  - [x] Test
  - [x] E2E
- [x] UI best practices adhered to 
- [x] Commits squashed (2-3 commits per PR maximum, 1 is ideal)
- [x] Commit(s) have meaningful message
##
- [ ] _(Optional) Release: Hold merge - not ready to be deployed to stage_
- [ ] _(Optional) QE: Needs QE attention (OUIA changed, percieved impact to tests, no test coverage)_
- [ ] _(Optional) QE: Has been mentioned_
- [ ] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)?_
- [ ] _(Optional) UX: Has been mentioned_
##

### CODE REVIEW

**Comment by florkbr** [comment]
@fhlavac how does this look to you?

**Comment by fhlavac** [comment]
### Description




I am proposing we add the H1 heading "foobar" to the PR template as requested in the ticket linked below. To see the change, you can preview the PR template in this PR.

[RHCLOUD-XXXXX](https://issues.redhat.com/browse/RHCLOUD-XXXXX)

---

### Screenshots



#### Before:
image

#### After:
image

---

### Checklist ☑️
- [x] PR only fixes one issue or story 
- [x] Diff reviewed for extraneous code 
- [x] UI best practices adhered to 
- [x] Commits squashed and with meaningful messages 
- [x] All PR checks pass locally (build, lint, test, E2E)

##
- [ ] _(Optional) QE: Needs QE attention (OUIA changed, percieved impact to tests, no test coverage)_
- [ ] _(Optional) QE: Has been mentioned_
- [ ] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [ ] _(Optional) UX: Has been mentioned_
##

**Comment by fhlavac** [comment]
@florkbr looks good! Tried to make it a bit smaller ^^

Hold merge could be replaced with marking as draft/label. What do you think?

Also, we've talked with Karel that local PR check sections may not be needed. If the check fails in the PR, it should not be reviewed and merged. Dev should also check locally, but when he doesn't, it probably does not hurt so much since the failure will be visible here anyway. Maybe it's better to get rid of 5 checkboxes in this case. Thoughts?

**Comment by florkbr** [comment]
@fhlavac @karelhala the simplified version looks good - however I personally feel we should have explicit checkboxes for each check or at minimum the general process we expect developers to run locally - even if they're enforced in the pipeline. I think this serves several purposes:
1. Reminds developers to run these locally - especially in repos that may have different commands for each of these "steps" or repos that do not have these steps (makes tech debt more obvious)
2. Drives consistency in the engineers process and mental model when developing code locally
3. Makes clear the MVP of opening a PR in our repos (while our engineers may already do this, new engineers or engineers from outside the team may not know the process)
4. Allows us to more easily identify if we have a process issue or a disconnect with our engineers/pipeline if the checkboxes are all checked and the PR is failing
5. Not that it's a big issue for our repos - but this checklist aids in reducing wasted CICD cycles and congestion for PRs that are not ready/failing locally.

We could also use something like https://typicode.github.io/husky/ to enforce these checks are run before commits if we don't want the checklist, but that would require updating every repo to use it.

**Comment by karelhala** [comment]
Let's meet in the middle and add checkbox for `All PR checks pass locally`. No need to list all of them, because some of them will be different in some repositories. But this checkbox will at least stop the dev and let them think about PR checks and what it does.

Please let's not use husky. Whenever I've seen husky I had to remove it, because commit ammends run these as well and often times they break and I am unable to push even a draft PR.

**Comment by fhlavac** [comment]
Sounds good to me!

**Comment by florkbr** [comment]
@karelhala @fhlavac sounds good to me too (single checkbox for PR checks pass locally). I also agree we should avoid Husky unless completely necessary - I'm just pointing out it is another tool in our toolbox :)

**Pull request closed without merging**
